# ============================================
# DEPLOYMENT - Gestión de Pods
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: order-service
  labels:
    app: order-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
              name: http

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"

            # Referencias a ConfigMap
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef: {name: order-service-config, key: PRODUCT_SERVICE_URL}
            - name: DB_URL
              valueFrom:
                configMapKeyRef: {name: order-service-config, key: DB_URL}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef: {name: order-service-config, key: SPRING_KAFKA_BOOTSTRAP_SERVERS}
            - name: DDL_AUTO
              valueFrom:
                configMapKeyRef: {name: order-service-config, key: DDL_AUTO}
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef: {name: order-service-config, key: LOG_LEVEL}
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef: {name: order-service-config, key: JAVA_OPTS}

            # Referencias a Secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef: {name: order-service-secret, key: DB_USERNAME}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: {name: order-service-secret, key: DB_PASSWORD}