# ============================================
# Prometheus Configuration (Docker Compose Mode)
# ============================================

global:
  scrape_interval: 15s          # Cada 15 segundos consulta las métricas
  evaluation_interval: 15s      # Cada 15 segundos evalúa reglas

scrape_configs:

  # Prometheus se monitorea a sí mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # order-service (Alcanzado mediante port-forward local)
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'order-service'

  # payment-service (Alcanzado mediante port-forward local)
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'payment-service'

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
        - targets: ['host.docker.internal:8085'] #
          labels:
            application: 'delivery-service'